name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  font_awesome_flutter: ^10.1.0
  curved_navigation_bar: ^1.0.6
  http: ^1.2.2
  dropdown_search: ^6.0.1
  easy_localization: ^3.0.7
  country_icons: ^3.0.0
  country_flags: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/
    - assets/
    - assets/language/
